name: Some Snakes Some Ladders

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-4-dev pkg-config build-essential gcc g++ lcov

      - name: Build with Coverage
        run: |
          gcc -fprofile-arcs -ftest-coverage `pkg-config --cflags gtk4` -o snakeLadders main.c game_setting.c generate_board.c drawSnakesAndLadders.c `pkg-config --libs gtk4` -lm
          chmod +x snakeLadders

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: Some Snakes Some Ladders
          path: ./snakeLadders

  test: # a test job
    runs-on: ubuntu-latest # using ubuntu
    steps:
      - uses: actions/checkout@v4 # check out the repo

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-4-dev pkg-config build-essential gcc g++ lcov

      - name: Build with Coverage
        run: |
          make testGame

      - name: Run Tests # subtask name
        run: |
          ./testGame # run the test executable 
          gcov testApp.c game_setting.c generate_board.c drawSnakesAndLadders.c # generate the gcov reports

      - name: Upload Test Results # subtask name
        if: ${{ always() }}  # do this even if the previous subtask returned a fail code
        uses: actions/upload-artifact@v4 # this is an upload task
        with:
          name: Test Results # artifact name
          path: ./test_results.txt # upload the test results

      - name: Upload Coverage Reports # subtask name
        if: ${{ always() }}  # do this even if the previous subtask returned a fail code
        uses: actions/upload-artifact@v4 # this is an upload task
        with:
          name: Coverage Reports # artifact name
          path: ./*.gcov # upload the gcov reports

