name: Some Snakes Some Ladders

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-4-dev pkg-config build-essential

      - name: Build snakeLadders
        run: |
          gcc `pkg-config --cflags gtk4` -o snakeLadders main.c game_setting.c generate_board.c drawSnakesAndLadders.c `pkg-config --libs gtk4` -lm
          chmod +x snakeLadders

      - name: Debug Build Issues (if any)
        if: failure()
        run: |
          echo "Build failed. Debugging logs:"
          cat /var/log/syslog | tail -n 50

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Some Snakes Some Ladders
          path: ./snakeLadders


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-4-dev pkg-config build-essential xvfb

          # we need to download the dependinces to be able to run the GUI to test
      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - name: Run GUI Application
        run: |
          ./snakeLadders &
          sleep 5
          echo "GUI Test Completed" # Modify as needed to test functionality

      - name: Capture Logs
        if: failure()
        run: |
          echo "Test failed. Debugging logs:"
          cat /var/log/syslog | tail -n 50
