name: Some Snakes Some Ladders

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-4-dev pkg-config build-essential

      - name: Build snakeLadders
        run: |
          gcc `pkg-config --cflags gtk4` -o snakeLadders main.c game_setting.c generate_board.c `pkg-config --libs gtk4`
          chmod +x snakeLadders

      - name: Debug Build Issues (if any)
        if: failure()
        run: |
          echo "Build failed. Debugging logs:"
          cat /var/log/syslog | tail -n 50

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Some Snakes Some Ladders
          path: ./snakeLadders


  #test:
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout repository
      #  uses: actions/checkout@v4

      #- name: Install dependencies
       # run: |
         # sudo apt update
          #sudo apt install -y libgtk-4-dev pkg-config build-essential

      #- name: Build and run tests
        #run: |
         # gcc `pkg-config --cflags gtk4` -o snakesNladders generate_board.c `pkg-config --libs gtk4`
         # ./snakesNladders > test_results.txt

      #- name: Upload Test Results
        #if: ${{ always() }}
        #uses: actions/upload-artifact@v4
        #with:
          #name: Test Results
          #path: ./test_results.txt
